version: '3.1'

services:

  mongo:
    image: mongo:4.2.6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/toaivo/mongo/db:/data/db
      - /home/toaivo/mongo/configdb:/data/configdb
